codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
    patch:
      default:
        target: 100%
        threshold: 0%

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

ignore:
  - "tests/*"
