codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch:
      default:
        target: 100%
        threshold: 0%

ignore:
  - "tests/*"
